package me.ethanbrews.xprituals.recipe

import me.ethanbrews.xprituals.block.enchantPedestal.EnchantPedestalRecipe
import me.ethanbrews.xprituals.item.StaffOfKnowledge
import me.ethanbrews.xprituals.item.StaffOfKnowledge2
import me.ethanbrews.xprituals.registry.ModEnchantments
import me.ethanbrews.xprituals.registry.ModItems
import net.minecraft.enchantment.Enchantments
import net.minecraft.item.ItemStack
import net.minecraft.item.Items

object EnchantPedestalRecipes {
    private val minecraftEnchantments = listOf(
        EnchantPedestalRecipe.getRecipe(
            Enchantments.FORTUNE,
            listOf(Items.EMERALD, Items.EMERALD, Items.EMERALD_BLOCK, Items.EMERALD_BLOCK),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.AQUA_AFFINITY,
            listOf(Items.DIAMOND_PICKAXE, Items.PRISMARINE_SHARD, Items.PRISMARINE_SHARD, Items.GOLD_BLOCK),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.CHANNELING,
            listOf(
                Items.LIGHTNING_ROD,
                Items.LIGHTNING_ROD,
                Items.PRISMARINE_SHARD,
                Items.PRISMARINE_SHARD,
                Items.GOLD_INGOT,
                Items.GOLD_INGOT,
                Items.PRISMARINE_CRYSTALS,
                Items.PRISMARINE_CRYSTALS
            ),
            10
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.BANE_OF_ARTHROPODS,
            listOf(Items.SPIDER_EYE, Items.SPIDER_EYE, Items.GOLDEN_SWORD, Items.STRING),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.BINDING_CURSE,
            listOf(Items.STRING, Items.STRING, Items.HONEYCOMB, Items.HONEYCOMB),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.BLAST_PROTECTION,
            listOf(
                Items.TNT,
                Items.TNT,
                Items.OBSIDIAN,
                Items.OBSIDIAN,
                Items.DEEPSLATE,
                Items.DEEPSLATE,
                Items.DEEPSLATE,
                Items.DEEPSLATE
            ),
            5
        ), EnchantPedestalRecipe.getRecipe(
            Enchantments.DEPTH_STRIDER,
            listOf(Items.PRISMARINE_SHARD, Items.PRISMARINE_SHARD, Items.SUGAR, Items.SUGAR),
            6
        ), EnchantPedestalRecipe.getRecipe(
            Enchantments.EFFICIENCY,
            listOf(
                Items.GOLDEN_PICKAXE,
                Items.GOLDEN_PICKAXE,
                Items.REDSTONE_BLOCK,
                Items.REDSTONE_BLOCK,
                Items.GLOWSTONE,
                Items.GLOWSTONE,
                Items.SUGAR,
                Items.SUGAR
            ),
            7
        ), EnchantPedestalRecipe.getRecipe(
            Enchantments.FEATHER_FALLING,
            listOf(Items.HAY_BLOCK, Items.FEATHER, Items.HONEY_BLOCK, Items.SLIME_BLOCK),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.FIRE_ASPECT,
            listOf(
                Items.BLAZE_ROD,
                Items.BLAZE_ROD,
                Items.MAGMA_BLOCK,
                Items.MAGMA_BLOCK,
                Items.FIRE_CHARGE,
                Items.FIRE_CHARGE,
                Items.COAL,
                Items.COAL
            ),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.FIRE_PROTECTION,
            listOf(
                Items.ICE,
                Items.ICE,
                Items.SNOWBALL,
                Items.SNOWBALL,
                Items.REDSTONE,
                Items.REDSTONE,
                Items.REDSTONE,
                Items.REDSTONE
            ),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.FIRE_PROTECTION,
            listOf(
                Items.PACKED_ICE,
                Items.PACKED_ICE,
                Items.SNOWBALL,
                Items.SNOWBALL,
                Items.REDSTONE,
                Items.REDSTONE,
                Items.REDSTONE,
                Items.REDSTONE
            ),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.FLAME,
            listOf(
                Items.ARROW,
                Items.ARROW,
                Items.BLAZE_POWDER,
                Items.BLAZE_POWDER,
                Items.REDSTONE,
                Items.REDSTONE,
                Items.REDSTONE,
                Items.REDSTONE
            ),
            10
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.FROST_WALKER,
            listOf(
                Items.ICE,
                Items.ICE,
                Items.ICE,
                Items.ICE,
                Items.COBBLESTONE,
                Items.COBBLESTONE,
                Items.COBBLESTONE,
                Items.COBBLESTONE
            ),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.FROST_WALKER,
            listOf(
                Items.PACKED_ICE,
                Items.PACKED_ICE,
                Items.PACKED_ICE,
                Items.PACKED_ICE,
                Items.COBBLESTONE,
                Items.COBBLESTONE,
                Items.COBBLESTONE,
                Items.COBBLESTONE
            ),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.IMPALING,
            listOf(
                Items.PUFFERFISH,
                Items.SALMON,
                Items.COD,
                Items.TROPICAL_FISH,
                Items.QUARTZ,
                Items.QUARTZ,
                Items.QUARTZ,
                Items.QUARTZ
            ),
            15
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.INFINITY,
            listOf(
                Items.ENDER_PEARL,
                Items.ENDER_PEARL,
                Items.BLAZE_POWDER,
                Items.BLAZE_POWDER,
                Items.ARROW,
                Items.ARROW,
                Items.REDSTONE,
                Items.REDSTONE
            ),
            20
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.KNOCKBACK,
            listOf(Items.GUNPOWDER, Items.SLIME_BLOCK, Items.SLIME_BLOCK, Items.GUNPOWDER),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.LOOTING,
            listOf(Items.RABBIT_FOOT, Items.DIAMOND, Items.GOLD_INGOT, Items.GOLD_INGOT),
            10
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.LOYALTY,
            listOf(
                Items.BONE,
                Items.WHEAT_SEEDS,
                Items.WHEAT,
                Items.WHEAT,
                Items.PRISMARINE_SHARD,
                Items.PRISMARINE_SHARD,
                Items.EMERALD,
                Items.EMERALD
            ),
            15
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.LUCK_OF_THE_SEA,
            listOf(Items.RABBIT_FOOT, Items.PUFFERFISH, Items.TROPICAL_FISH, Items.TRIPWIRE_HOOK),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.LURE,
            listOf(Items.COD, Items.SALMON, Items.STRING, Items.STRING),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.MENDING,
            listOf(
                Items.MOSSY_COBBLESTONE,
                Items.MOSSY_COBBLESTONE,
                Items.EMERALD_BLOCK,
                Items.EMERALD_BLOCK,
                Items.STRING,
                Items.STRING,
                Items.STRING,
                Items.STRING
            ),
            30
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.MULTISHOT,
            listOf(
                Items.ARROW,
                Items.ARROW,
                Items.ARROW,
                Items.ARROW,
                Items.ARROW,
                Items.ARROW,
                Items.GUNPOWDER,
                Items.SLIME_BLOCK
            ),
            10
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.PIERCING,
            listOf(
                Items.QUARTZ,
                Items.QUARTZ,
                Items.PRISMARINE_SHARD,
                Items.PRISMARINE_SHARD,
                Items.REDSTONE,
                Items.REDSTONE,
                Items.REDSTONE,
                Items.REDSTONE
            ),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.POWER,
            listOf(Items.IRON_BLOCK, Items.IRON_BLOCK, Items.SLIME_BLOCK, Items.SLIME_BLOCK),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.PROJECTILE_PROTECTION,
            listOf(Items.SHIELD, Items.ARROW, Items.ARROW, Items.SHIELD),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.PUNCH,
            listOf(
                Items.GUNPOWDER,
                Items.SLIME_BLOCK,
                Items.SLIME_BLOCK,
                Items.GUNPOWDER,
                Items.ARROW,
                Items.ARROW,
                Items.ARROW,
                Items.ARROW
            ),
            10
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.QUICK_CHARGE,
            listOf(
                Items.SUGAR,
                Items.SUGAR,
                Items.SUGAR,
                Items.SUGAR,
                Items.ARROW,
                Items.ARROW,
                Items.ARROW,
                Items.ARROW
            ),
            15
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.RESPIRATION,
            listOf(
                Items.TORCH,
                Items.TORCH,
                Items.PUFFERFISH,
                Items.PUFFERFISH,
                Items.MAGMA_BLOCK,
                Items.MAGMA_BLOCK,
                Items.TORCH,
                Items.TORCH
            ),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.RIPTIDE,
            listOf(
                Items.SLIME_BLOCK,
                Items.SUGAR,
                Items.SUGAR,
                Items.SUGAR,
                Items.PRISMARINE_SHARD,
                Items.PRISMARINE_SHARD,
                Items.PRISMARINE_CRYSTALS,
                Items.PRISMARINE_CRYSTALS
            ),
            20
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.SHARPNESS,
            listOf(
                Items.QUARTZ,
                Items.QUARTZ,
                Items.QUARTZ,
                Items.QUARTZ,
                Items.IRON_SWORD,
                Items.IRON_SWORD,
                Items.REDSTONE,
                Items.REDSTONE
            ),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.SILK_TOUCH,
            listOf(
                Items.STRING,
                Items.STRING,
                Items.WHITE_WOOL,
                Items.WHITE_WOOL,
                Items.EMERALD,
                Items.EMERALD,
                Items.GOLD_INGOT,
                Items.GOLD_INGOT
            ),
            15
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.SMITE,
            listOf(
                Items.ROTTEN_FLESH,
                Items.ROTTEN_FLESH,
                Items.ROTTEN_FLESH,
                Items.ROTTEN_FLESH,
                Items.SUGAR,
                Items.SUGAR,
                Items.REDSTONE,
                Items.REDSTONE
            ),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.SOUL_SPEED,
            listOf(Items.SOUL_SAND, Items.SOUL_SAND, Items.SUGAR, Items.SUGAR),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.SWEEPING,
            listOf(
                Items.IRON_SWORD,
                Items.IRON_SWORD,
                Items.QUARTZ,
                Items.QUARTZ,
                Items.IRON_HOE,
                Items.IRON_HOE,
                Items.GLOWSTONE_DUST,
                Items.GLOWSTONE_DUST
            ),
            10
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.THORNS,
            listOf(Items.ROSE_BUSH, Items.ROSE_BUSH, Items.AMETHYST_SHARD, Items.AMETHYST_SHARD),
            10
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.UNBREAKING,
            listOf(
                Items.OBSIDIAN,
                Items.OBSIDIAN,
                Items.OBSIDIAN,
                Items.OBSIDIAN,
                Items.IRON_BLOCK,
                Items.IRON_BLOCK,
                Items.DEEPSLATE,
                Items.DEEPSLATE
            ),
            10
        ),
        EnchantPedestalRecipe.getRecipe(
            Enchantments.VANISHING_CURSE,
            listOf(Items.COBWEB, Items.COBWEB, Items.REDSTONE, Items.REDSTONE),
            5
        )
    )
    private val modEnchantments = listOf(
        EnchantPedestalRecipe.getRecipe(
            ModEnchantments.endWeightEnchantment,
            listOf(Items.ANVIL, Items.ENDER_PEARL, Items.ENDER_PEARL, Items.ENDER_PEARL),
            5
        ),
        EnchantPedestalRecipe.getRecipe(
            ModEnchantments.xpBoostEnchantment,
            listOf(
                ModItems.zombie_brains,
                ModItems.zombie_brains,
                ModItems.zombie_brains,
                ModItems.zombie_brains,
                Items.GOLD_INGOT,
                Items.GOLD_INGOT,
                Items.GOLD_INGOT,
                Items.GOLD_INGOT
            ),
            10
        )
    )
    private val modItems = listOf(
        EnchantPedestalRecipe(
            { item, _ -> item.item is StaffOfKnowledge },
            { ItemStack(ModItems.tier2Staff) },
            listOf(Items.NETHER_STAR, Items.DIAMOND, Items.NETHER_STAR, Items.DIAMOND),
            10,
            true
        ).withOutputRecipeName("Staff of Greater Knowledge")
    )

    val allRecipes = minecraftEnchantments + modEnchantments + modItems
}